spring:
    application:
        name: pass-web
    datasource:
        url: jdbc:mysql://localhost:3306/firstproject_db?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
        cache: false

    sql:
        init:
            data-locations: classpath:insert.sql
            mode: always

    jpa:
        hibernate:
            ddl-auto: create
        generate-ddl: true
        show-sql: true
        defer-datasource-initialization: true
    mvc:
        view:
            prefix: /templates/
            suffix: .html
        mustache:
            prefix: /templates/
            suffix: .mustache
            expose-session-attributes: true